-- AFTER RUNNING THIS SHEET, GO BACK TO JUPYTER NOTEBOOK TO SHOW THE ACTUAL TRANSFORMATIONS

use role sysadmin;
use schema demo.telco;
use warehouse lab_s_wh;


select * from raw_parquet;

CREATE OR REPLACE TABLE DEMOGRAPHICS
(
CUSTOMERID VARCHAR,
COUNT NUMBER,
GENDER VARCHAR,
SENIORCITIZEN BOOLEAN,
PARTNER BOOLEAN,
DEPENDENTS BOOLEAN
);


CREATE OR REPLACE TABLE LOCATION
(
CUSTOMERID VARCHAR,
COUNTRY VARCHAR,
STATE VARCHAR,
CITY VARCHAR,
ZIPCODE NUMBER,
LATLONG VARCHAR,
LATITUDE VARCHAR,
LONGITUDE VARCHAR
);


CREATE OR REPLACE TABLE SERVICES
(
  CUSTOMERID VARCHAR,
  TENUREMONTHS NUMBER,
  PHONESERVICE BOOLEAN,
  MULTIPLELINES VARCHAR,
  INTERNETSERVICE VARCHAR,
  ONLINESECURITY VARCHAR,
  ONLINEBACKUP VARCHAR,
  DEVICEPROTECTION VARCHAR,
  TECHSUPPORT VARCHAR,
  STREAMINGTV VARCHAR,
  STREAMINGMOVIES VARCHAR,
  CONTRACT VARCHAR,
  PAPERLESSBILLING BOOLEAN,
  PAYMENTMETHOD VARCHAR,
  MONTHLYCHARGES FLOAT,
  TOTALCHARGES DOUBLE
);

CREATE OR REPLACE TABLE STATUS
(
CUSTOMERID VARCHAR,
CHURNLABEL BOOLEAN,
CHURNVALUE FLOAT,
CHURNSCORE NUMBER,
CLTV NUMBER,
CHURNREASON VARCHAR
);


